server.port=55551
spring.datasource.url=jdbc:mysql://103.18.6.46:3306/qmhqla07t4y1_personal_finance?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=qmhqla07t4y1_admin
spring.datasource.password=Son@mym@140899